### ISSUE TITLE
AttributeError: 'F24_Device' object has no attribute 'deviceList'

### ISSUE THREAD

**Issue by jflorian** [clumens/pykickstart#232]
I got the following traceback in a Koji livemedia job:

~~~
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/koji/daemon.py", line 1244, in runTask
    response = (handler.run(),)
  File "/usr/lib/python2.7/site-packages/koji/tasks.py", line 307, in run
    return koji.util.call_with_argcheck(self.handler, self.params, self.opts)
  File "/usr/lib/python2.7/site-packages/koji/util.py", line 209, in call_with_argcheck
    return func(*args, **kwargs)
  File "/usr/sbin/kojid", line 3217, in handler
    self.readKickstart(kspath, opts)
  File "/usr/sbin/kojid", line 2747, in readKickstart
    self.ks.readKickstart(kspath)
  File "/usr/lib/python2.7/site-packages/pykickstart/parser.py", line 815, in readKickstart
    self.readKickstartFromString(s, reset=False)
  File "/usr/lib/python2.7/site-packages/pykickstart/parser.py", line 788, in readKickstartFromString
    self._stateMachine(i)
  File "/usr/lib/python2.7/site-packages/pykickstart/parser.py", line 771, in _stateMachine
    self._tryFunc(lambda: self.handleCommand(lineno, args))
  File "/usr/lib/python2.7/site-packages/pykickstart/parser.py", line 682, in _tryFunc
    fn()
  File "/usr/lib/python2.7/site-packages/pykickstart/parser.py", line 771, in <lambda>
    self._tryFunc(lambda: self.handleCommand(lineno, args))
  File "/usr/lib/python2.7/site-packages/pykickstart/parser.py", line 573, in handleCommand
    retval = self.handler.dispatcher(args, lineno)
  File "/usr/lib/python2.7/site-packages/pykickstart/base.py", line 379, in dispatcher
    lst = self.commands[cmd].dataList()
  File "/usr/lib/python2.7/site-packages/pykickstart/commands/device.py", line 161, in dataList
    return self.deviceList
AttributeError: 'F24_Device' object has no attribute 'deviceList'
~~~

**Comment by poncovka** [comment]
Hi, this issues should be fixed in the commit  https://github.com/clumens/pykickstart/commit/086e82ce2516e2c18ec6be237cb6df67cb6c3b4d. Which version of pykickstart is it?

**Comment by jflorian** [comment]
@poncovka this would have been with python2-kickstart-3.12-4.fc28.noarch.

**Comment by jflorian** [comment]
Can this be made available in F28 testing pretty please?  According to bodhi, it looks like 3.12-4 is still the newest.

**Comment by jkonecny12** [comment]
@clumens what do you think, could that break something?

**Comment by clumens** [comment]
There's a fair bit of changes from 3.12 to master, not least of which is adding F29 support and deprecating a bunch of stuff.  I'd probably lean towards just grabbing the patch needed to fix this and doing a new build.

**Comment by clumens** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=28345867 is done - I can do an update if that is required.

**Comment by jflorian** [comment]
Thanks for rushing that out Chris!  Let me give that a test.  I've only got one Koji builder that needs this so a formal update isn't necessary for just me.  I'll post my results but I'm presently battling mock which refuses to allow a necessary network connection for a critical livemedia job, so it may be a while.

**Comment by jflorian** [comment]
@clumens that build is working fine for me.  Thanks again.  I'm closing this issue, but obviously you may reopen if you wish to track this any further.
